# Generated by Django 5.1.1 on 2024-10-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
