# Generated by Django 5.1.1 on 2024-10-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('answers', models.TextField()),
            ],
            options={
                'db_table': 'event_registration',
                'managed': False,
            },
        ),
    ]
