# Generated by Django 5.1.1 on 2024-10-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('full_details', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('total_tickets', models.IntegerField()),
                ('questions', models.JSONField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
    ]
