# Generated by Django 5.1.1 on 2024-10-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_eventregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={},
        ),
    ]
