# Generated by Django 5.1.1 on 2024-10-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_eventregistration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'managed': False},
        ),
    ]
