# Generated by Django 5.1.1 on 2024-10-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'eventuser',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
