# Generated by Django 5.1.2 on 2024-10-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'managed': False},
        ),
    ]
