# Generated by Django 5.1.2 on 2024-10-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_otp_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otp',
            table='OTP',
        ),
    ]
